# Generated by Django 5.2 on 2025-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('dataset', 'Dataset'), ('code', 'Code'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField()),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
