# Generated by Django 5.2 on 2025-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_summary', models.TextField()),
                ('conclusion', models.TextField()),
                ('significance', models.CharField(choices=[('breakthrough', 'Breakthrough'), ('significant', 'Significant'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('negative', 'Negative')], max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('citations_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'findings',
                'ordering': ['-created_at'],
            },
        ),
    ]
