# Generated by Django 5.2 on 2025-06-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likes', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='publications.publication'),
        ),
    ]
